name: Release

on:
  push:
    tags:
    - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      POETRY_HOME: /opt/poetry

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '>=3.10'

      # see: https://python-poetry.org/docs/#ci-recommendations
      - name: Install and Build
        shell: bash
        run: |
          python3 -m venv $POETRY_HOME
          $POETRY_HOME/bin/pip install poetry==1.7.1
          $POETRY_HOME/bin/poetry --version
          $POETRY_HOME/bin/poetry config virtualenvs.create "false"
          $POETRY_HOME/bin/poetry version ${{ github.ref_name }}
          $POETRY_HOME/bin/poetry build

      # see: https://github.com/python-poetry/poetry/blob/master/.github/workflows/release.yml
      # TODO License, for this tiny bit of CI, maybe?
      - name: Check Version
        id: check-version
        run: |
          [[ "$(poetry version --short)" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]] || echo prerelease=true >> $GITHUB_OUTPUT

      # (same note on source as check-version)
      - name: Create Release
        uses: ncipollo/release-action@v1.13.0  # Aug 24 2023
        with:
          artifacts: "dist/*"
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: false
          prerelease: steps.check-version.outputs.prerelease == 'true'
