name: Release


# Adapted from:
# https://github.com/python-poetry/poetry/blob/master/.github/workflows/release.yml
# License: MIT License (https://github.com/python-poetry/poetry/blob/master/LICENSE)

on:
  push:
    tags:
    - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python - -y

      - name: Update PATH
        run: echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Build project for distribution
        run: poetry build

      - name: Check Version
        id: check-version
        run: |
          [[ "$(poetry version --short)" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]] || echo prerelease=true >> $GITHUB_OUTPUT

      # (same note on source as check-version)
      - name: Create Release
        uses: ncipollo/release-action@v1.13.0  # Aug 24 2023
        with:
          artifacts: "dist/*"
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: false
          prerelease: steps.check-version.outputs.prerelease == 'true'

      # Publish to PyPI via PyPA 'best practice'
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1.8.10  # Aug 10 2023
